# Generated by Django 6.0.2 on 2026-03-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='client_name',
            field=models.CharField(default='Unknown Client', max_length=255),
            preserve_default=False,
        ),
    ]
