# Generated by Django 6.0.2 on 2026-03-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemplateDocument',
            new_name='Draft',
        ),
    ]
