# Generated by Django 6.0.2 on 2026-02-27 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_matter_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(max_length=255)),
                ('hearing_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_dates', to='practice.matter')),
            ],
        ),
    ]
